name: Deploy to NAS

on:
  push:
    branches:
      - main   # 필요하면 여기에 다른 브랜치 추가 가능
  workflow_dispatch: # 수동 실행도 가능

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Sync files to NAS
        run: |
          TARGET_DIR="/mnt/khdpSample/kcd2025/main"
          echo "Deploying to $TARGET_DIR ..."
          rsync -av --delete \
            --exclude='.github/' \
            --exclude='.git/' \
            --exclude='*.yml' \
            ./ "$TARGET_DIR/"
